# symfony 6 controller support ( mostly unused )
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Main Routes
Home:
    path: /
    controller: App\Controller\IndexController::index
app_logout:
    path: /logout
    methods: GET

# Admin Routes
app_admin:
    path: /admin
    controller: App\Controller\AdminController::page

# CRUD User
admin_user:
    path: /admin/user
    controller: App\Controller\Admin\UserController::index
admin_user_add:
    path: /admin/user/add
    controller: App\Controller\Admin\UserController::add
admin_user_edit:
    path: /admin/user/{id}/edit
    controller: App\Controller\Admin\UserController::edit
admin_user_delete:
    path: /admin/user/{id}/delete
    controller: App\Controller\Admin\UserController::delete
admin_user_delete_confirm:
    path: /admin/user/{id}/delete/confirm
    controller: App\Controller\Admin\UserController::confirmDelete

# CRUD Project
admin_project:
    path: /admin/project
    controller: App\Controller\Admin\ProjectController::index
admin_project_add:
    path: /admin/project/add
    controller: App\Controller\Admin\ProjectController::add
admin_project_edit:
    path: /admin/project/{id}/edit
    controller: App\Controller\Admin\ProjectController::edit
admin_project_delete:
    path: /admin/project/{id}/delete
    controller: App\Controller\Admin\ProjectController::delete
admin_project_delete_confirm:
    path: /admin/project/{id}/delete/confirm
    controller: App\Controller\Admin\ProjectController::confirmDelete

# CRUD Devices
admin_device:
    path: /admin/devices
    controller: App\Controller\Admin\DeviceController::index
admin_device_add:
    path: /admin/devices/add
    controller: App\Controller\Admin\DeviceController::add
admin_device_edit:
    path: /admin/devices/{id}/edit
    controller: App\Controller\Admin\DeviceController::edit
admin_device_delete:
    path: /admin/devices/{id}/delete
    controller: App\Controller\Admin\DeviceController::delete
admin_device_delete_confirm:
    path: /admin/devices/{id}/delete/confirm
    controller: App\Controller\Admin\DeviceController::confirmDelete

# Project page
admin_edit_project:
    path: /admin/edit_project/{project}
    controller: App\Controller\Admin\EditProject\EditProjectController::index

# CRUD Locations
admin_location_add:
    path: /admin/edit_project/{project}/location/add
    controller: App\Controller\Admin\EditProject\LocationController::add
admin_location_edit:
    path: /admin/edit_project/{project}/location/{location}/edit
    controller: App\Controller\Admin\EditProject\LocationController::edit
admin_location_delete:
    path: /admin/edit_project/{project}/location/{location}/delete
    controller: App\Controller\Admin\EditProject\LocationController::delete
admin_location_delete_confirm:
    path: /admin/edit_project/{project}/location/{location}/delete/confirm
    controller: App\Controller\Admin\EditProject\LocationController::confirmDelete

# CRUD questions
admin_question:
    path: /admin/edit_project/{project}/question
    controller: App\Controller\Admin\EditProject\QuestionController::index
admin_question_add:
    path: /admin/edit_project/{project}/question/add
    controller: App\Controller\Admin\EditProject\QuestionController::add
admin_question_edit:
    path: /admin/edit_project/{project}/question/{question}/edit
    controller: App\Controller\Admin\EditProject\QuestionController::edit
admin_question_delete:
    path: /admin/edit_project/{project}/question/{question}/delete
    controller: App\Controller\Admin\EditProject\QuestionController::delete
admin_question_delete_confirm:
    path: /admin/edit_project/{project}/question/{question}/delete/confirm
    controller: App\Controller\Admin\EditProject\QuestionController::confirmDelete

# Game
game_device:
    path: /device/{guid}
    controller: App\Controller\Game\GameController::index