controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_admin:
    path: /admin
    controller: App\Controller\AdminController::page
Home:
    path: /
    controller: App\Controller\IndexController::index
app_logout:
    path: /logout
    methods: GET
