# symfony 6 controller support ( mostly unused )
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Main Routes
Home:
    path: /
    controller: App\Controller\IndexController::index
app_logout:
    path: /logout
    methods: GET

# Admin Routes
app_admin:
    path: /admin
    controller: App\Controller\AdminController::page

# CRUD User
admin_user:
    path: /Admin/user
    controller: App\Controller\Admin\UserController::index
admin_user_add:
    path: /Admin/user/add
    controller: App\Controller\Admin\UserController::add
admin_user_edit:
    path: /Admin/user/{id}/edit
    controller: App\Controller\Admin\UserController::edit
admin_user_delete:
    path: /Admin/user/{id}/delete
    controller: App\Controller\Admin\UserController::delete
admin_user_delete_confirm:
    path: /Admin/user/{id}/delete/confirm
    controller: App\Controller\Admin\UserController::confirmDelete

# CRUD Project
admin_project:
    path: /Admin/project
    controller: App\Controller\Admin\ProjectController::index
admin_project_create:
    path: /Admin/project/create
    controller: App\Controller\Admin\ProjectController::add